### PR TITLE
translation(cht)added

### PR DESCRIPTION
**Pull request by frenchdixco**

### CODE REVIEW

**Comment by Mhburg** [comment]
Very much appreciate your work.
我看了一下翻譯文件，裏面有部分英文并沒有翻譯。你可以把剩下的也翻譯了嗎？
我想提供一個更完整的翻譯體驗給玩家，謝謝。
麻煩你了。

**Comment by frenchdixco** [comment]
I understand that and totally agree with you. The problem is I can't find where these label show up in game so can't give it a proper translation. The label are 
<AwesomeInventory_MassCarried>Mass carried</AwesomeInventory_MassCarried>
<Corgi_ForcedHold>Forced holding</Corgi_ForcedHold>
and the whole  part.
Please tell me where can i find them in game so no mistranslate are provided

**Comment by Mhburg** [comment]
I have updated language keys and removed unused ones. Please check commit eb61d047ee70755052f103219303035935a8b011

**Comment by Mhburg** [comment]
Language keys in the description section is used as a tooltip when players pick items from the right panel in the loadout window. It was not properly displayed before.

**Comment by frenchdixco** [comment]
Done:)
simplified Chinese included .
btw the ascetic option seems not working for me

**Comment by Mhburg** [comment]
It is a WIP. I hide that option in the latest version.

**Comment by Mhburg** [comment]
LFCR in tags will be carried over to display leaving a rather awkward empty line at the beginning of tooltip text. I have made changed to them.

**Comment by Mhburg** [comment]
Thanks for your contribution.

**Pull request merged**
